--- #YAML:1.0
name:               Class-TLB
version:            0.01
abstract:           Transparent load balancing for any resource class.
author:
    - Jerome Eteve <jerome@eteve.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    List::PriorityQueue:  0.01
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
